downgrade the Java runtime
Exception in thread "main" java.lang.NoClassDefFoundError:
javax/xml/bind/annotation/XmlSchema

https://stackoverflow.com/questions/49683488/how-to-fix-exception-in-th
read-main-java-lang-noclassdeffounderror-javax-xml

The thing has been removed from Java 11